sudo: false
language: ruby
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
before_install:
  - gem install bundler -v 1.16.1
  - if [ ! -e "$HOME/.cargo/bin" ]; then curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y; fi
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup default stable
  - rustc --version
